/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  TourathNativeExperiences as PrismaTourathNativeExperiences,
} from "@prisma/client";

export class TourathNativeExperiencesServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TourathNativeExperiencesCountArgs, "select">
  ): Promise<number> {
    return this.prisma.tourathNativeExperiences.count(args);
  }

  async tourathNativeExperiencesItems(
    args: Prisma.TourathNativeExperiencesFindManyArgs
  ): Promise<PrismaTourathNativeExperiences[]> {
    return this.prisma.tourathNativeExperiences.findMany(args);
  }
  async tourathNativeExperiences(
    args: Prisma.TourathNativeExperiencesFindUniqueArgs
  ): Promise<PrismaTourathNativeExperiences | null> {
    return this.prisma.tourathNativeExperiences.findUnique(args);
  }
  async createTourathNativeExperiences(
    args: Prisma.TourathNativeExperiencesCreateArgs
  ): Promise<PrismaTourathNativeExperiences> {
    return this.prisma.tourathNativeExperiences.create(args);
  }
  async updateTourathNativeExperiences(
    args: Prisma.TourathNativeExperiencesUpdateArgs
  ): Promise<PrismaTourathNativeExperiences> {
    return this.prisma.tourathNativeExperiences.update(args);
  }
  async deleteTourathNativeExperiences(
    args: Prisma.TourathNativeExperiencesDeleteArgs
  ): Promise<PrismaTourathNativeExperiences> {
    return this.prisma.tourathNativeExperiences.delete(args);
  }
}
